In [1]:
include("main_whit.jl")

LU_decompose (generic function with 1 method)

In [2]:
n = 8
D = ddmat(1:n, 3)
display(D)

M = diagm(ones(n)) + λ * D' * D

5×8 SparseMatrixCSC{Int64, Int64} with 20 stored entries:
 -1   3  -3   1   ⋅   ⋅   ⋅  ⋅
  ⋅  -1   3  -3   1   ⋅   ⋅  ⋅
  ⋅   ⋅  -1   3  -3   1   ⋅  ⋅
  ⋅   ⋅   ⋅  -1   3  -3   1  ⋅
  ⋅   ⋅   ⋅   ⋅  -1   3  -3  1

8×8 Matrix{Num}:
   1.0 + λ   -3λ            3λ          …     0.0          0.0
 -3λ           1.0 + 10λ  -12λ                0.0          0.0
  3λ        -12λ             1.0 + 19λ        0.0          0.0
  -λ          6λ          -15λ               -λ            0.0
   0.0        -λ            6λ               6λ           -λ
   0.0         0.0          -λ          …  -12λ           3λ
   0.0         0.0           0.0              1.0 + 10λ  -3λ
   0.0         0.0           0.0            -3λ            1.0 + λ

In [3]:
U = deepcopy(M)
L = typeof(U)(diagm(ones(n)))

# 仅运行三次，猜测公式的形式
for i = 1:3
    r1 = U[i, :]
    for j = i+1:min(i+2, n)
        f = U[j, i] / U[i, i]
        L[j, i] = f
        U[j, :] .= U[j, :] .- (f * r1)
    end
end
## U
## Elier采用的是LU分解 
display(L)
display(U)


8×8 Matrix{Num}:
          1.0       …  0.0  0.0  0.0  0.0  0.0
 (-3λ) / (1.0 + λ)     0.0  0.0  0.0  0.0  0.0
  (3λ) / (1.0 + λ)     0.0  0.0  0.0  0.0  0.0
          0.0          1.0  0.0  0.0  0.0  0.0
          0.0          0.0  1.0  0.0  0.0  0.0
          0.0       …  0.0  0.0  1.0  0.0  0.0
          0.0          0.0  0.0  0.0  1.0  0.0
          0.0          0.0  0.0  0.0  0.0  1.0

8×8 Matrix{Num}:
  1.0 + λ  -3λ                                  …     0.0          0.0
  0          1.0 + (-9(λ^2)) / (1.0 + λ) + 10λ        0.0          0.0
  0          0                                        0.0          0.0
 -λ          0                                       -λ            0.0
  0.0       -λ                                       6λ           -λ
  0.0        0.0                                …  -12λ           3λ
  0.0        0.0                                      1.0 + 10λ  -3λ
  0.0        0.0                                    -3λ            1.0 + λ

In [ ]:
# U = deepcopy(M)
# L,U = LU_decompose(U)
# L

In [4]:
r = lu(M)
## lu采用for循环的形式，
r.L
# r.U

8×8 Matrix{Num}:
          1         …  0
 (-3λ) / (1.0 + λ)     0
  (3λ) / (1.0 + λ)     0
  (-λ) / (1.0 + λ)     0
          0.0          0
          0.0       …  0
          0.0          0
          0.0          1