In [2]:
include("main_whit.jl")

cofactor (generic function with 3 methods)

In [3]:
n = 6
w = variables(:w, 1:n)
D = ddmat(1:n, 2)
# M = diagm(ones(n))
M = diag_m(w[1:n]) + λ * D' * D
display(M)
# M = diagm(W) + λ * D' * D

U = deepcopy(M)
L = typeof(U)(diagm(ones(n)))

r = lu(M)
## lu采用for循环的形式，
r.L

6×6 Matrix{Num}:
 w₁ + λ        -2λ          λ          0.0        0.0       0.0
    -2λ    w₂ + 5λ        -4λ          λ          0.0       0.0
      λ        -4λ    w₃ + 6λ        -4λ          λ         0.0
      0.0        λ        -4λ    w₄ + 6λ        -4λ         λ
      0.0        0.0        λ        -4λ    w₅ + 5λ       -2λ
      0.0        0.0        0.0        λ        -2λ    w₆ + λ

6×6 Matrix{Num}:
                1    …  0
 (-2λ) / (w₁ + λ)       0
     λ / (w₁ + λ)       0
                0.0     0
                0.0     0
                0.0  …  1

In [7]:
r.U

6×6 Matrix{Num}:
 w_1 + λ  …                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

8×8 Matrix{Num}:
          1         …  0
 (-2λ) / (1.0 + λ)     0
     λ / (1.0 + λ)     0
          0.0          0
          0.0          0
          0.0       …  0
          0.0          0
          0.0          1