In [2]:
# 使用LDL'分解，求解Whittaker smoother (d=3)
# 根据该代码，归纳总结出whit3的向量公式
# 采用a1, a2，混合代入，或许能得到更简洁的公式
# Dongdong Kong, CUG, 2024-05-06
include("main_whit.jl")

cofactor (generic function with 3 methods)

In [4]:
n = 7

w = variables(:w, 1:n)
D = ddmat(1:n, 3)

# M = diagm(ones(n))
M = diag_m(w[1:n]) + λ * D' * D
display(M)
# M = diagm(W) + λ * D' * D
# inv(M)
# U = deepcopy(M)
# L = typeof(U)(diagm(ones(n)));

r = lu(M)
r.L
# diag(r.U)[1:n]

7×7 Matrix{Num}:
 w₁ + λ         -3λ          3λ          -λ         0.0         0.0       0.0
    -3λ    w₂ + 10λ        -12λ          6λ        -λ           0.0       0.0
     3λ        -12λ    w₃ + 19λ        -15λ        6λ          -λ         0.0
     -λ          6λ        -15λ    w₄ + 20λ      -15λ          6λ        -λ
      0.0        -λ          6λ        -15λ  w₅ + 19λ        -12λ        3λ
      0.0         0.0        -λ          6λ      -12λ    w₆ + 10λ       -3λ
      0.0         0.0         0.0        -λ        3λ         -3λ    w₇ + λ

7×7 Matrix{Num}:
                1    …  0
 (-3λ) / (w₁ + λ)       0
  (3λ) / (w₁ + λ)       0
  (-λ) / (w₁ + λ)       0
                0.0     0
                0.0  …  0
                0.0     1

## 2. 一种更简明的公式推导方法

In [57]:
d = variables(:d, 1:n)
c = variables(:c, 1:n)
e = variables(:e, 1:n)
f = variables(:f, 1:n)

U = deepcopy(M)
L = typeof(U)(diagm(ones(n)))

## Elier采用的是LU分解 
# 仅运行三次，猜测公式的形式
for i = 1:n-1
    r1 = U[i, :]
    j = i+1
    c[i] = U[j, i] / d[i]
    L[j, i] = c[i] # ci, ei
    U[j, :] .= U[j, :] .- (c[i] * r1)
    d[i] = U[i, i]
    
    j = i+2
    j > n && continue
    e[i] = U[j, i] / U[i, i]
    L[j, i] = e[i] # ci, ei
    U[j, :] .= U[j, :] .- (e[i] * r1)

    j = i+3
    j > n && continue
    f[i] = U[j, i] / U[i, i]
    L[j, i] = f[i] # ci, ei
    U[j, :] .= U[j, :] .- (f[i] * r1)
    # for j = i+1:min(i+2, n)
    #     f = U[j, i] / U[i, i]
    #     L[j, i] = f # ci, ei
    #     U[j, :] .= U[j, :] .- (f * r1)
    # end
end

## Elier采用的是LU分解 
display(L)
# display(U)


7×7 Matrix{Num}:
               1.0  …  0.0
      (-3λ) / d₁       0.0
 (3λ) / (w₁ + λ)       0.0
 (-λ) / (w₁ + λ)       0.0
               0.0     0.0
               0.0  …  0.0
               0.0     1.0

In [58]:
d

7-element Vector{Num}:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

In [ ]:
# U = deepcopy(M)
# L,U = LU_decompose(U)
# L